### ISSUE TITLE
Autdit Logs

### ISSUE THREAD

**Issue by pi0** [bakjs/bak#4]
Created PR #5

**Comment by siavashkavousi** [comment]
what is target and target_type? (gonna use for finding?)

**Comment by pi0** [comment]
@siavashkavousi Yep, Something like this: 
```js
{
  target: '1343fba324436',
  target_type: 'Ticket'
}
```

This allows us dynamically get appreciate model.

**Comment by siavashkavousi** [comment]
what about required fields? (I know we would lose potential flexibility)

**Comment by pi0** [comment]
Please explain more about required thing. This log entries are going to be created with our well controlled plugin not directly by users.

**Comment by siavashkavousi** [comment]
I think target, target_type and action are required in every log. 

> log entries are going ... 

That's ok then :+1:

**Comment by Tabrizian** [comment]
@pi0 I think that the model is pretty perfect and general. You mean we want to add a Hapi logging plugin for developers API?

**Comment by pi0** [comment]
To enable Audit We need add an empty audit section to log config:
```js
    log: {
        sentry: {
            dsn: null
        },
        audit: {}
    }
```

Usage in hapi : 
```js
request.audit({target: t, action: 'READ', payload: 'bar'});
```

Target Model is auto detected :)

Simple mongo entry: 
```js
{ 
    "_id" : ObjectId("58ecbf4d949be6254889c553"), 
    "user" : ObjectId("58b9821a59543c1e54a11a19"), 
    "ip" : "127.0.0.1", 
    "target" : ObjectId("58c022de0e540d001206884b"), 
    "action" : "READ", 
    "payload" : "bar", 
    "target_model" : "Ticket", 
    "created_at" : ISODate("2017-04-11T11:34:37.295+0000")
}
```

**Comment by pi0** [comment]
Now we need some helper methods in order to get log entries, @siavashkavousi @Tabrizian What is your idea about functions usage API ?

**Comment by Tabrizian** [comment]
@pi0 How does it auto detect target_model?! :astonished:

**Comment by pi0** [comment]
See audit/index.js:9

**Comment by siavashkavousi** [comment]
Current findBy impl supports both finding audits with specific target and action, any comment?

**Comment by pi0** [comment]
@siavashkavousi Yep, I've seen that. Maybe we can even generalize it further more. For example, allow query all logs related to specific department or user. (findBy is not satisfying enough:D ) also function naming is confusing!
